name: Build test

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependencies
      run: |
        sudo apt install -y ruby-dev
        sudo gem install fpm

    - name: build on x86
      run: |
        sudo apt update 
        sudo apt install -y build-essential tree
        make clean
        make
        mkdir -p /lib/modules/6.2.0-1018-azure/kernel/drivers/net/wireless/
        make install
        ls

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: ".ko x86"
        path: |
          /lib/modules/6.2.0-1018-azure/kernel/drivers/net/wireless/*
